create schema if not exists private;
revoke all on schema private from public;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format check (
    username is null or (
      username = lower(username)
      and username ~ '^[a-z0-9][a-z0-9._-]{2,29}$'
      and username not in (
        'admin','api','auth','login','signup','dashboard','settings','onboarding',
        'pricing','templates','support','help','biofy'
      )
    )
  )
);

create unique index profiles_username_lower_idx
  on public.profiles(lower(username))
  where username is not null;

create table public.public_profiles (
  username text primary key,
  display_name text,
  avatar_url text,
  bio text,
  updated_at timestamptz not null default now()
);

create table public.pages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  username text unique,
  template text not null default 'minimal',
  theme jsonb not null default '{}'::jsonb,
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index pages_public_username_idx
  on public.pages(username)
  where is_published = true;

create table public.page_blocks (
  id uuid primary key default gen_random_uuid(),
  page_id uuid not null references public.pages(id) on delete cascade,
  type text not null default 'link',
  title text,
  url text,
  config jsonb not null default '{}'::jsonb,
  position integer not null default 0 check (position >= 0),
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index page_blocks_page_position_idx
  on public.page_blocks(page_id, position);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free','pro','business')),
  status text not null default 'active',
  interval text not null default 'monthly',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  page_id uuid not null references public.pages(id) on delete cascade,
  block_id uuid references public.page_blocks(id) on delete set null,
  kind text not null check (kind in ('view','click')),
  referrer text,
  created_at timestamptz not null default now()
);

create index analytics_events_page_created_idx
  on public.analytics_events(page_id, created_at desc);

create index analytics_events_block_created_idx
  on public.analytics_events(block_id, created_at desc)
  where block_id is not null;

alter table public.profiles enable row level security;
alter table public.public_profiles enable row level security;
alter table public.pages enable row level security;
alter table public.page_blocks enable row level security;
alter table public.subscriptions enable row level security;
alter table public.analytics_events enable row level security;

create policy profiles_owner_select
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

create policy profiles_owner_insert
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy profiles_owner_update
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy profiles_owner_delete
  on public.profiles for delete
  to authenticated
  using ((select auth.uid()) = id);

create policy public_profiles_read
  on public.public_profiles for select
  to anon, authenticated
  using (true);

create policy pages_public_read
  on public.pages for select
  to anon, authenticated
  using (is_published = true and username is not null);

create policy pages_owner_read
  on public.pages for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy pages_owner_insert
  on public.pages for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy pages_owner_update
  on public.pages for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy pages_owner_delete
  on public.pages for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy blocks_public_read
  on public.page_blocks for select
  to anon, authenticated
  using (
    is_visible = true
    and exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.is_published = true
        and p.username is not null
    )
  );

create policy blocks_owner_read
  on public.page_blocks for select
  to authenticated
  using (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  );

create policy blocks_owner_insert
  on public.page_blocks for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  );

create policy blocks_owner_update
  on public.page_blocks for update
  to authenticated
  using (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  );

create policy blocks_owner_delete
  on public.page_blocks for delete
  to authenticated
  using (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  );

create policy subscriptions_owner_read
  on public.subscriptions for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy analytics_public_insert
  on public.analytics_events for insert
  to anon, authenticated
  with check (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.is_published = true
        and p.username is not null
    )
    and (
      block_id is null
      or exists (
        select 1
        from public.page_blocks b
        where b.id = block_id
          and b.page_id = analytics_events.page_id
          and b.is_visible = true
      )
    )
  );

create policy analytics_owner_read
  on public.analytics_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.pages p
      where p.id = page_id
        and p.user_id = (select auth.uid())
    )
  );

revoke all on public.profiles from anon, authenticated;
revoke all on public.public_profiles from anon, authenticated;
revoke all on public.pages from anon, authenticated;
revoke all on public.page_blocks from anon, authenticated;
revoke all on public.subscriptions from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

grant select, insert, update, delete on public.profiles to authenticated;
grant select on public.public_profiles to anon, authenticated;
grant select (id, username, template, theme, is_published, published_at, created_at, updated_at)
  on public.pages to anon, authenticated;
grant insert (user_id) on public.pages to authenticated;
grant update (template, theme, is_published, published_at) on public.pages to authenticated;
grant delete on public.pages to authenticated;
grant select, insert, update, delete on public.page_blocks to authenticated;
grant select on public.page_blocks to anon;
grant select on public.subscriptions to authenticated;
grant insert (page_id, block_id, kind, referrer)
  on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

grant all on public.profiles to service_role;
grant all on public.public_profiles to service_role;
grant all on public.pages to service_role;
grant all on public.page_blocks to service_role;
grant all on public.subscriptions to service_role;
grant all on public.analytics_events to service_role;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function private.set_updated_at();

create trigger pages_set_updated_at
  before update on public.pages
  for each row execute function private.set_updated_at();

create trigger blocks_set_updated_at
  before update on public.page_blocks
  for each row execute function private.set_updated_at();

create trigger subscriptions_set_updated_at
  before update on public.subscriptions
  for each row execute function private.set_updated_at();

create or replace function private.sync_public_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.username is not null then
      delete from public.public_profiles where username = old.username;
    end if;
    return old;
  end if;

  if tg_op = 'UPDATE'
     and old.username is not null
     and old.username is distinct from new.username then
    delete from public.public_profiles where username = old.username;
  end if;

  if new.username is not null then
    insert into public.public_profiles (username, display_name, avatar_url, bio, updated_at)
    values (new.username, new.display_name, new.avatar_url, new.bio, now())
    on conflict (username) do update set
      display_name = excluded.display_name,
      avatar_url = excluded.avatar_url,
      bio = excluded.bio,
      updated_at = excluded.updated_at;
  end if;

  update public.pages set username = new.username where user_id = new.id;
  return new;
end;
$$;

revoke all on function private.sync_public_profile() from public;

create trigger profiles_sync_public
  after insert or update or delete on public.profiles
  for each row execute function private.sync_public_profile();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'display_name',
      new.raw_user_meta_data->>'full_name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;

  insert into public.pages (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.subscriptions (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

create or replace function public.is_username_available(candidate text)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select
    candidate = lower(candidate)
    and candidate ~ '^[a-z0-9][a-z0-9._-]{2,29}$'
    and candidate not in (
      'admin','api','auth','login','signup','dashboard','settings','onboarding',
      'pricing','templates','support','help','biofy'
    )
    and not exists (
      select 1
      from public.public_profiles
      where username = candidate
    );
$$;

revoke all on function public.is_username_available(text) from public;
grant execute on function public.is_username_available(text) to anon, authenticated;
